// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

/// @title LibAddressRegistryReleased
/// @notice Every frozen release of `AddressRegistry`: one entry per file in
/// the append-only `src/generated/<tag>/` record, in tag order.
///
/// The deploy address, code hash, creation code and runtime code of each
/// entry are aliased from that release's own frozen snapshot, so the
/// consensus record is read from the immutable file and from nowhere else.
///
/// The key, the artifact path and the dependencies are explorer and ordering
/// metadata regenerated from the CURRENT declaration, and are not part of
/// that record. A moved source path retroactively updates every entry's
/// artifact path, which is intended: the alternative is parsing this
/// generated file back in to preserve what it last said.
library LibAddressRegistryReleased {
    /// Every frozen release, in tag order.
    /// @return suites The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory suites) {
        suites = new DeploySuite[](0);
    }
}
