// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as ADDRESS_REGISTRY_ADDR,
    BYTECODE_HASH as ADDRESS_REGISTRY_HASH
} from "../generated/candidate/AddressRegistry.sol";

/// @title LibAddressRegistryDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `AddressRegistry`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibAddressRegistryDeploy {
    address constant ADDRESS_REGISTRY_DEPLOYED_ADDRESS = ADDRESS_REGISTRY_ADDR;
    bytes32 constant ADDRESS_REGISTRY_DEPLOYED_CODEHASH = ADDRESS_REGISTRY_HASH;
}
