// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

/// @title LibAddressRegistryDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `AddressRegistry`. The Zoltu factory is `CREATE2` over its calldata with a
/// zero salt, so the address is a pure function of the creation code and is
/// identical on every network.
///
/// Both values are derived from the creation code this repo compiles, under
/// this repo's own compiler settings, and are checked against it by
/// `AddressRegistryDeployPinsTest` — the contract, the settings that compile it
/// and the pins that describe it are all here, so there is no boundary across
/// which they can silently diverge.
///
/// The root authority is a constant in that creation code, so changing the root
/// moves both values.
///
/// HAND-WRITTEN FOR NOW. From the first `sol-v*` release this file is
/// regenerated by `script/BuildPointers.sol`, aliasing the frozen
/// `src/generated/<tag>/AddressRegistry.pointers.sol` snapshot so that snapshot
/// is the single source of truth. It already lives at the import path the
/// generated version will occupy, so consumers' imports do not move. No
/// snapshot is frozen yet because `ADDRESS_REGISTRY_ROOT` is still a
/// placeholder and `src/generated/<tag>/` is append-only: a snapshot written
/// now could never be corrected.
library LibAddressRegistryDeploy {
    /// @dev The deterministic deploy address of `AddressRegistry` when deployed
    /// via the Zoltu factory.
    address constant ADDRESS_REGISTRY_DEPLOYED_ADDRESS = 0x0B8CAaDADF7c53a1b0Af8A7A8E7F3ca90DE517d6;

    /// @dev The code hash of `AddressRegistry` once deployed, i.e. `keccak256`
    /// over the runtime code its creation code leaves behind.
    bytes32 constant ADDRESS_REGISTRY_DEPLOYED_CODEHASH =
        0xd9a6a2f03c1e1851becfedba819a436dcccc81c40ac8df02be6815f0b261d042;
}
