// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as MIGRATION_REGISTRY_ADDR,
    BYTECODE_HASH as MIGRATION_REGISTRY_HASH
} from "../generated/candidate/MigrationRegistry.sol";

/// @title LibMigrationRegistryDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `MigrationRegistry`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibMigrationRegistryDeploy {
    address constant MIGRATION_REGISTRY_DEPLOYED_ADDRESS = MIGRATION_REGISTRY_ADDR;
    bytes32 constant MIGRATION_REGISTRY_DEPLOYED_CODEHASH = MIGRATION_REGISTRY_HASH;
}
