// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.
//
// It is committed to the repository because there is a circular dependency
// between the contract and its generated file. The contract needs the
// generated file to exist so that it can compile, and the generated file
// needs the contract to exist so that it can be compiled.
//
// ...except this particular file is not autogenerated. It is a hand-written
// EXEMPLAR of a file that is, carrying that header because reproducing the
// header is part of reproducing the shape. See below.

// THE EXEMPLAR OWNS THE SHAPE. THE COMPILER OWNS THE VALUES.
//
// This file is HAND-WRITTEN, and that is the point. It is the authority on what
// a generated deploy snapshot LOOKS like — which constants exist, of what type,
// in what order, under what header, with no reference to the contract they came
// from — and `GeneratedSnapshotShapeTest` checks the real generator's committed
// output against it.
//
// It is evidence about the generator ONLY because the generator did not produce
// it, exactly as a slow reference implementation is evidence about a fast one
// only when it was derived independently. Regenerate this file from the
// generator and the conformance test collapses into a determinism check that
// passes however far both have drifted.
//
// What to do when something here goes red:
//
// - a compiler or optimiser change moved the VALUES: update the literals below
//   by hand. `RainDeployVerifyOfflineTest::testDeployPinsInternallyConsistent`
//   fails with both the stored and the derived value in its message — paste the
//   derived one. Four literals, and a wrong paste is caught immediately by that
//   same derivation check, which is why machine-producing them would buy
//   nothing and cost the test.
// - the generator started emitting a DIFFERENT SHAPE by accident: fix
//   `script/Build.sol`. Do not touch this file; it is the thing being conformed
//   to.
// - you want a different shape deliberately: change this file and the generator
//   in one commit. The conformance test proves they agree.
//
// Shape disputes are settled here. Value disputes are settled by the compiler.
// They never contest the same thing.

/// @dev Hash of the known bytecode.
bytes32 constant BYTECODE_HASH = bytes32(0x0cff4019cbc9f3009ec77b6438233bbe4c5d991a5766aa56c97dbb593feb3663);

/// @dev The deterministic deploy address of the contract when deployed via
/// the Zoltu factory.
address constant DEPLOYED_ADDRESS = address(0x0c04367b381F8Ca252aD2516F1Eac2b9B2ca928F);

/// @dev The creation bytecode of the contract.
bytes constant CREATION_CODE =
    hex"6080604052602a5f553480156012575f80fd5b50604380601e5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c80633fa4f24514602a575b5f80fd5b60315f5481565b60405190815260200160405180910390f3";

/// @dev The runtime bytecode of the contract.
bytes constant RUNTIME_CODE =
    hex"6080604052348015600e575f80fd5b50600436106026575f3560e01c80633fa4f24514602a575b5f80fd5b60315f5481565b60405190815260200160405180910390f3";
