// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

import {DeployCandidate, DeploySuite, RainDeploySuitesBase} from "./RainDeploySuitesBase.sol";
import {AddressRegistry} from "../concrete/AddressRegistry.sol";
import {MigrationRegistry} from "../concrete/MigrationRegistry.sol";
import {
    CREATION_CODE as ADDRESS_REGISTRY_CREATION_CODE_CANDIDATE,
    RUNTIME_CODE as ADDRESS_REGISTRY_RUNTIME_CODE_CANDIDATE
} from "../generated/candidate/AddressRegistry.sol";
import {
    CREATION_CODE as MIGRATION_REGISTRY_CREATION_CODE_CANDIDATE,
    RUNTIME_CODE as MIGRATION_REGISTRY_RUNTIME_CODE_CANDIDATE
} from "../generated/candidate/MigrationRegistry.sol";
import {LibAddressRegistryDeploy} from "../lib/LibAddressRegistryDeploy.sol";
import {LibAddressRegistryReleased} from "../lib/LibAddressRegistryReleased.sol";
import {LibMigrationRegistryDeploy} from "../lib/LibMigrationRegistryDeploy.sol";
import {LibMigrationRegistryReleased} from "../lib/LibMigrationRegistryReleased.sol";

/// @title RegistryDeploySuites
/// @notice Everything this repo deploys, declared ONCE.
///
/// Three contracts inherit this and nothing else declares a suite:
///
/// - `script/Deploy.sol` broadcasts from it
/// - `RegistryDeploySnapshotTest` checks its records against its creation code
/// - `RegistryDeployChainTest` checks it against every chain
///
/// So "the deploy script broadcasts one contract while the tests verify
/// another" is not a thing that can be true here. Not because something checks
/// for it — because there is only one list, and all three read it.
///
/// It lives in `src/` rather than `test/` for two reasons. `.soldeerignore`
/// excludes `test/`, and a downstream `script/` has to import its own
/// equivalent. And in THIS repo the deployment process is the product: see the
/// scoped exception recorded in `CLAUDE.md`.
///
/// This declaration is the whole of what a deploy repo writes. The derivation,
/// the comparisons, the source anchor, the networks matrix and the broadcast
/// are all inherited. There is deliberately nothing per suite beyond an array
/// entry and nothing per network at all.
///
/// Half of it is written by hand and half is generated: the candidates below
/// are the declaration, and the released libs come from `script/Build.sol`,
/// which emits them from the frozen record.
abstract contract RegistryDeploySuites is RainDeploySuitesBase {
    /// @inheritdoc RainDeploySuitesBase
    /// @dev Generated by `script/Build.sol` from the frozen
    /// `src/generated/<tag>/` record, in the same call that writes it. The
    /// record and the declaration of it therefore cannot disagree — which
    /// matters because a release missing from the declaration is a release
    /// every check quietly stops asking about, while the whole suite stays
    /// green.
    ///
    /// One generated lib per deployed contract, concatenated here, because
    /// `writeReleasedSuitesLib` emits the releases of ONE contract: a release
    /// freezes every contract it names into a single tag directory, so a lib
    /// that took the record whole would give another contract's snapshot this
    /// contract's suite key and collide with its own entry for that tag.
    ///
    /// Both are empty until the first release is cut. The rolling `candidate/`
    /// snapshots are not releases and do exist.
    function releasedSuites() internal pure override returns (DeploySuite[] memory suites) {
        DeploySuite[] memory addressRegistry = LibAddressRegistryReleased.releasedSuites();
        DeploySuite[] memory migrationRegistry = LibMigrationRegistryReleased.releasedSuites();

        suites = new DeploySuite[](addressRegistry.length + migrationRegistry.length);
        for (uint256 i = 0; i < addressRegistry.length; i++) {
            suites[i] = addressRegistry[i];
        }
        for (uint256 i = 0; i < migrationRegistry.length; i++) {
            suites[addressRegistry.length + i] = migrationRegistry[i];
        }
    }

    /// @inheritdoc RainDeploySuitesBase
    /// @dev One entry per contract this repo deploys. A third deployed contract
    /// is a third named candidate below, a third entry here, and a third entry
    /// in `script/Build.sol`'s generated-contract list — nothing else.
    function candidateSuites() internal pure override returns (DeployCandidate[] memory candidates) {
        candidates = new DeployCandidate[](2);
        candidates[0] = addressRegistryCandidate();
        candidates[1] = migrationRegistryCandidate();
    }

    /// This repo's rolling `AddressRegistry` candidate.
    ///
    /// The pins in `LibAddressRegistryDeploy` are aliased from the generated
    /// snapshot, and they are what the internal group checks the derivation
    /// against and what the broadcast asserts against before it forks anything.
    ///
    /// The creation code and runtime code are RECORDED, read from the rolling
    /// `src/generated/candidate/` snapshot. That is what makes the source
    /// anchor mean something: it compares the recorded creation code against
    /// `type(AddressRegistry).creationCode`, so editing the contract without
    /// re-running `script/Build.sol` fails. While nothing was recorded, that
    /// check compared source against itself and could only pass.
    ///
    /// `AddressRegistry` reads nothing and calls nothing at construction, so it
    /// has no dependency that must already be on chain.
    ///
    /// Named rather than reached by index into `candidateSuites`, because
    /// `script/Build.sol` needs THIS candidate specifically — a released-suites
    /// lib describes one contract — and a positional read silently describes a
    /// different contract the moment the list is reordered. Naming it here also
    /// keeps the suite key, the artifact path and the dependency list spelled
    /// once: `Build.sol` inherits this rather than restating them.
    /// @return The candidate.
    function addressRegistryCandidate() internal pure returns (DeployCandidate memory) {
        return DeployCandidate({
            snapshot: DeploySuite({
                suite: "address-registry",
                creationCode: ADDRESS_REGISTRY_CREATION_CODE_CANDIDATE,
                storedDeployedAddress: LibAddressRegistryDeploy.ADDRESS_REGISTRY_DEPLOYED_ADDRESS,
                storedBytecodeHash: LibAddressRegistryDeploy.ADDRESS_REGISTRY_DEPLOYED_CODEHASH,
                storedRuntimeCode: ADDRESS_REGISTRY_RUNTIME_CODE_CANDIDATE,
                artifactPath: "src/concrete/AddressRegistry.sol:AddressRegistry",
                dependencies: new address[](0)
            }),
            sourceCreationCode: type(AddressRegistry).creationCode
        });
    }

    /// This repo's rolling `MigrationRegistry` candidate.
    ///
    /// Everything said about the `AddressRegistry` candidate holds here
    /// unchanged: the pins are aliased from the generated snapshot, the
    /// creation and runtime code are recorded rather than derived, and the
    /// source anchor is what says the record describes THIS contract.
    ///
    /// `MigrationRegistry` has no constructor argument, no compile-time
    /// authority and no dependency to be on chain first — the namespace is
    /// `msg.sender`, so there is nothing to configure and nothing to resolve.
    /// That is also why it is deployable to a new network the day the network
    /// is added, with no follow-up transaction to make it useful.
    /// @return The candidate.
    function migrationRegistryCandidate() internal pure returns (DeployCandidate memory) {
        return DeployCandidate({
            snapshot: DeploySuite({
                suite: "migration-registry",
                creationCode: MIGRATION_REGISTRY_CREATION_CODE_CANDIDATE,
                storedDeployedAddress: LibMigrationRegistryDeploy.MIGRATION_REGISTRY_DEPLOYED_ADDRESS,
                storedBytecodeHash: LibMigrationRegistryDeploy.MIGRATION_REGISTRY_DEPLOYED_CODEHASH,
                storedRuntimeCode: MIGRATION_REGISTRY_RUNTIME_CODE_CANDIDATE,
                artifactPath: "src/concrete/MigrationRegistry.sol:MigrationRegistry",
                dependencies: new address[](0)
            }),
            sourceCreationCode: type(MigrationRegistry).creationCode
        });
    }
}
