// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

import {DeployCandidate, DeploySuite, RainDeploySuitesBase} from "./RainDeploySuitesBase.sol";
import {AddressRegistry} from "../concrete/AddressRegistry.sol";
import {
    CREATION_CODE as ADDRESS_REGISTRY_CREATION_CODE_CANDIDATE,
    RUNTIME_CODE as ADDRESS_REGISTRY_RUNTIME_CODE_CANDIDATE
} from "../generated/candidate/AddressRegistry.sol";
import {LibAddressRegistryDeploy} from "../lib/LibAddressRegistryDeploy.sol";
import {LibAddressRegistryReleased} from "../lib/LibAddressRegistryReleased.sol";

/// @title RegistryDeploySuites
/// @notice Everything this repo deploys, declared ONCE.
///
/// Three contracts inherit this and nothing else declares a suite:
///
/// - `script/Deploy.sol` broadcasts from it
/// - `AddressRegistryDeploySnapshotTest` checks its records against its
///   creation code
/// - `AddressRegistryDeployChainTest` checks it against every chain
///
/// So "the deploy script broadcasts one contract while the tests verify
/// another" is not a thing that can be true here. Not because something checks
/// for it — because there is only one list, and all three read it.
///
/// It lives in `src/` rather than `test/` for two reasons. `.soldeerignore`
/// excludes `test/`, and a downstream `script/` has to import its own
/// equivalent. And in THIS repo the deployment process is the product: see the
/// scoped exception recorded in `CLAUDE.md`.
///
/// This declaration is the whole of what a deploy repo writes. The derivation,
/// the comparisons, the source anchor, the networks matrix and the broadcast
/// are all inherited. There is deliberately nothing per suite beyond an array
/// entry and nothing per network at all.
///
/// Half of it is written by hand and half is generated: the candidate below is
/// the declaration, and `releasedSuites()` comes from `script/Build.sol`, which
/// emits it from the frozen record.
abstract contract RegistryDeploySuites is RainDeploySuitesBase {
    /// @inheritdoc RainDeploySuitesBase
    /// @dev Generated by `script/Build.sol` from the frozen
    /// `src/generated/<tag>/` record, in the same call that writes it. The
    /// record and the declaration of it therefore cannot disagree — which
    /// matters because a release missing from the declaration is a release
    /// every check quietly stops asking about, while the whole suite stays
    /// green.
    ///
    /// Empty until the first release is cut. The rolling `candidate/` snapshot
    /// is not a release and does exist.
    function releasedSuites() internal pure override returns (DeploySuite[] memory) {
        return LibAddressRegistryReleased.releasedSuites();
    }

    /// @inheritdoc RainDeploySuitesBase
    /// @dev One entry, because this repo deploys one contract. A second
    /// deployed contract is a second named candidate below, a second entry
    /// here, and a second snapshot in `script/Build.sol` — nothing else.
    function candidateSuites() internal pure override returns (DeployCandidate[] memory candidates) {
        candidates = new DeployCandidate[](1);
        candidates[0] = addressRegistryCandidate();
    }

    /// This repo's rolling `AddressRegistry` candidate.
    ///
    /// The pins in `LibAddressRegistryDeploy` are hand-written literals, and
    /// they are what the internal group checks the derivation against and what
    /// the broadcast asserts against before it forks anything.
    ///
    /// The creation code and runtime code are RECORDED, read from the rolling
    /// `src/generated/candidate/` snapshot. That is what makes the source
    /// anchor mean something: it compares the recorded creation code against
    /// `type(AddressRegistry).creationCode`, so editing the contract without
    /// re-running `script/Build.sol` fails. While nothing was recorded, that
    /// check compared source against itself and could only pass.
    ///
    /// `AddressRegistry` reads nothing and calls nothing at construction, so it
    /// has no dependency that must already be on chain.
    ///
    /// Named rather than reached by index into `candidateSuites`, because
    /// `script/Build.sol` needs THIS candidate specifically — a released-suites
    /// lib describes one contract — and a positional read silently describes a
    /// different contract the moment the list is reordered. Naming it here also
    /// keeps the suite key, the artifact path and the dependency list spelled
    /// once: `Build.sol` inherits this rather than restating them.
    /// @return The candidate.
    function addressRegistryCandidate() internal pure returns (DeployCandidate memory) {
        return DeployCandidate({
            snapshot: DeploySuite({
                suite: "address-registry",
                creationCode: ADDRESS_REGISTRY_CREATION_CODE_CANDIDATE,
                storedDeployedAddress: LibAddressRegistryDeploy.ADDRESS_REGISTRY_DEPLOYED_ADDRESS,
                storedBytecodeHash: LibAddressRegistryDeploy.ADDRESS_REGISTRY_DEPLOYED_CODEHASH,
                storedRuntimeCode: ADDRESS_REGISTRY_RUNTIME_CODE_CANDIDATE,
                artifactPath: "src/concrete/AddressRegistry.sol:AddressRegistry",
                dependencies: new address[](0)
            }),
            sourceCreationCode: type(AddressRegistry).creationCode
        });
    }
}
