// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test, Vm} from "forge-std-1.16.1/src/Test.sol";
import {DeployCandidate} from "../../../src/abstract/RainDeploySuitesBase.sol";
import {RegistryDeploySuites} from "../../../src/abstract/RegistryDeploySuites.sol";
import {LibRainDeploySnapshot} from "../../../src/lib/LibRainDeploySnapshot.sol";
import {LibStringSet} from "../../lib/LibStringSet.sol";

/// @title GeneratedSnapshotShapeTest
/// @notice What a generated deploy snapshot must look like, asserted against
/// the real generator's committed output.
///
/// THESE ASSERTIONS ARE THE SPECIFICATION. There is no second hand-written file
/// to compare against and therefore no question about that file's provenance:
/// "there is an `address` constant named `DEPLOYED_ADDRESS`" is stated here,
/// once, in test code, and checked against what `script/Build.sol` actually
/// emitted.
///
/// The check reads the compiler's AST rather than the source text, so it is
/// about the file's STRUCTURE and not its formatting. `forge build --ast`
/// writes the AST into the artifact JSON, and — usefully, since a snapshot
/// declares only file-level constants and no contract at all — foundry still
/// emits an artifact for such a file.
///
/// Values are deliberately not asserted. A solc or optimiser change moves every
/// literal without changing anything here, and a wrong literal is caught
/// immediately by the group 1 derivation checks in `RainDeployVerifySnapshot`.
///
/// EVERY rolling snapshot is checked, not the first one. The generator writes
/// one per contract this repo deploys, so a shape asserted about one of them is
/// a shape asserted about the generator only for as long as there is one; the
/// second contract is exactly where a hand edit lands unseen. The set comes
/// from the directory the generator writes to and is checked to be the same set
/// the declaration names, because a walk that found the wrong files is a loop
/// that passes while asserting nothing about the contracts this repo deploys.
contract GeneratedSnapshotShapeTest is RegistryDeploySuites, Test {
    /// The generated-file header every snapshot carries.
    string constant GENERATED_HEADER = "// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.";

    /// Every rolling snapshot the generator has written, by contract name.
    ///
    /// Read from the directory rather than listed here, so a contract added to
    /// the declaration is covered by these assertions without anybody
    /// remembering to add it — which is the failure mode a shape spec is least
    /// able to notice, since a file nobody checks looks exactly like a file
    /// that passes.
    /// @return names One entry per snapshot, e.g. `AddressRegistry`.
    function snapshotContractNames() internal view returns (string[] memory names) {
        Vm.DirEntry[] memory entries = vm.readDir(LibRainDeploySnapshot.dirForSnapshot(LibRainDeploySnapshot.CANDIDATE));

        names = new string[](entries.length);
        for (uint256 i = 0; i < entries.length; i++) {
            string[] memory components = vm.split(entries[i].path, "/");
            names[i] = vm.replace(components[components.length - 1], ".sol", "");
        }
    }

    /// The artifact for one generated snapshot, which carries its AST.
    /// @param contractName The contract the snapshot describes.
    /// @return The artifact path.
    function artifactPath(string memory contractName) internal pure returns (string memory) {
        return string.concat("out/", LibRainDeploySnapshot.CANDIDATE, "/", contractName, ".sol/", contractName, ".json");
    }

    /// The node types of a generated snapshot's source unit, in file order.
    ///
    /// Indexed one at a time rather than with a `$.ast.nodes[*].nodeType`
    /// wildcard: foundry's JSON path support requires a path to resolve to
    /// exactly one value, so the wildcard is rejected outright.
    /// @param contractName The contract the snapshot describes.
    /// @return types One entry per top-level AST node.
    function nodeTypes(string memory contractName) internal view returns (string[] memory types) {
        string memory json = vm.readFile(artifactPath(contractName));
        string[] memory found = new string[](64);
        uint256 count = 0;
        while (vm.keyExistsJson(json, string.concat("$.ast.nodes[", vm.toString(count), "].nodeType"))) {
            found[count] = vm.parseJsonString(json, string.concat("$.ast.nodes[", vm.toString(count), "].nodeType"));
            count++;
        }
        types = new string[](count);
        for (uint256 i = 0; i < count; i++) {
            types[i] = found[i];
        }
    }

    /// The declared constants of a generated snapshot, in file order, as
    /// `<type> <NAME>` — read from the AST, so formatting cannot affect it.
    /// @param contractName The contract the snapshot describes.
    /// @return declarations One entry per file-level constant.
    function constantDeclarations(string memory contractName) internal view returns (string[] memory declarations) {
        string memory json = vm.readFile(artifactPath(contractName));
        string[] memory types = nodeTypes(contractName);

        string[] memory found = new string[](types.length);
        uint256 count = 0;
        for (uint256 i = 0; i < types.length; i++) {
            if (keccak256(bytes(types[i])) != keccak256(bytes("VariableDeclaration"))) {
                continue;
            }
            string memory base = string.concat("$.ast.nodes[", vm.toString(i), "]");
            assertTrue(vm.parseJsonBool(json, string.concat(base, ".constant")), "snapshot declared a non-constant");
            found[count] = string.concat(
                vm.parseJsonString(json, string.concat(base, ".typeName.name")),
                " ",
                vm.parseJsonString(json, string.concat(base, ".name"))
            );
            count++;
        }
        declarations = new string[](count);
        for (uint256 i = 0; i < count; i++) {
            declarations[i] = found[i];
        }
    }

    /// The contract a candidate describes, taken from the `<path>:<Name>`
    /// artifact path it declares.
    ///
    /// That name is also the name of the candidate's rolling snapshot: the
    /// generator writes `src/generated/candidate/<Name>.sol`, and the
    /// declaration imports that exact file for its recorded creation code. A
    /// declaration and a generator that disagree about the name are a
    /// declaration whose snapshot is somebody else's.
    /// @param candidate The candidate to name.
    /// @return The contract name.
    function candidateContractName(DeployCandidate memory candidate) internal pure returns (string memory) {
        string[] memory components = vm.split(candidate.snapshot.artifactPath, ":");
        return components[components.length - 1];
    }

    /// PROPERTY: the rolling snapshots and the declared candidates are the same
    /// set, matched by name.
    ///
    /// Every other assertion here loops over the snapshots the walk found, and
    /// a loop over a short list passes. This is what says the list is neither
    /// short nor somebody else's: a candidate with no rolling snapshot is a
    /// contract whose generated shape nothing below checks, and a snapshot with
    /// no candidate is a record of something this repo no longer declares.
    ///
    /// Matched by name in both directions rather than by counting, because
    /// equal counts are also what a missing snapshot and a stale one left
    /// behind together produce, and that is the pair a walk of a directory is
    /// most likely to find. The counts are asserted as well, so two candidates
    /// naming one contract cannot pass by both matching its single snapshot.
    function testEveryCandidateHasASnapshot() external view {
        string[] memory snapshots = snapshotContractNames();
        DeployCandidate[] memory candidates = checkedCandidateSuites();

        string[] memory declared = new string[](candidates.length);
        for (uint256 i = 0; i < candidates.length; i++) {
            declared[i] = candidateContractName(candidates[i]);
        }

        assertEq(
            snapshots.length, declared.length, "a candidate has no rolling snapshot, or a snapshot has no candidate"
        );

        for (uint256 i = 0; i < declared.length; i++) {
            assertTrue(
                LibStringSet.holds(snapshots, declared[i]),
                string.concat("candidate has no rolling snapshot: ", declared[i])
            );
        }

        for (uint256 i = 0; i < snapshots.length; i++) {
            assertTrue(
                LibStringSet.holds(declared, snapshots[i]),
                string.concat("rolling snapshot has no candidate: ", snapshots[i])
            );
        }
    }

    /// PROPERTY: every declared artifact path RESOLVES — it is `<path>:<Name>`,
    /// the path is a file this repo has, and the artifact that whole string
    /// selects is the contract the candidate is anchored to.
    ///
    /// `artifactPath` is the one field of a suite that nothing derives, and
    /// until this assertion nothing checked either. It is load bearing twice
    /// over: `LibRainDeploy` prints it as the `forge verify-contract` command a
    /// human runs against a freshly broadcast contract, and
    /// `candidateContractName` above takes the contract this whole shape spec
    /// is about out of it. Only the `:<Name>` half was ever read by a check —
    /// `testEveryCandidateHasASnapshot` matches it against the generator's
    /// output — so a path left behind by a moved or renamed source file passed
    /// every assertion in this repo, including all of the ones here, because
    /// the half that moved is the half nothing read. `bytecode_hash = "none"`
    /// and `cbor_metadata = false` mean moving a file changes no creation code,
    /// no address and no code hash either, so there is nothing else for it to
    /// be caught by.
    ///
    /// Resolved through `vm.getCode`, which is foundry's own resolution of a
    /// `<path>:<Name>` artifact id — the same form `forge verify-contract`
    /// takes — rather than by searching the file's text for `contract <Name>`.
    /// A text search asserts formatting: it is satisfied by the name occurring
    /// in a comment or in a longer identifier, and defeated by a declaration
    /// written with no space before its brace.
    ///
    /// `vm.isFile` on the path half AS WELL, because `vm.getCode` resolves an
    /// artifact id by path SUFFIX while the printed command is run from the
    /// repo root. `concrete/AddressRegistry.sol:AddressRegistry` resolves for
    /// `vm.getCode` — uniquely, and to the right contract — and still names no
    /// file anybody can point `forge verify-contract` at. That is the one shape
    /// of wrong path nothing else in this repo goes red on.
    ///
    /// A path outside the `fs_permissions` roots fails here as a cheatcode
    /// revert naming the path rather than as this assertion's own message,
    /// which is foundry refusing to look rather than looking and not finding.
    ///
    /// Compared against the candidate's own `sourceCreationCode` rather than
    /// merely required to resolve to something, because resolving is not the
    /// same as resolving to the RIGHT contract. Two candidates whose declared
    /// paths are swapped resolve perfectly, and every other assertion in this
    /// repo stays green through it — including `testEveryCandidateHasASnapshot`
    /// above, because swapping both halves leaves the SET of declared names
    /// exactly as it was. This is the assertion that says each candidate's path
    /// names ITS own contract rather than one of its siblings'.
    ///
    /// Hashed rather than compared as bytes, for the reason
    /// `CandidateSourceMismatch` gives for hashing: creation codes run to tens
    /// of kilobytes, and a failure message carrying two of them is a failure
    /// message nobody reads.
    function testEveryCandidateArtifactPathResolves() external view {
        DeployCandidate[] memory candidates = checkedCandidateSuites();
        for (uint256 i = 0; i < candidates.length; i++) {
            string memory declared = candidates[i].snapshot.artifactPath;
            string[] memory parts = vm.split(declared, ":");

            assertEq(parts.length, 2, string.concat("artifact path is not <path>:<Name>: ", declared));
            assertTrue(vm.isFile(parts[0]), string.concat("artifact path names no such file: ", declared));
            assertEq(
                keccak256(vm.getCode(declared)),
                keccak256(candidates[i].sourceCreationCode),
                string.concat("artifact path resolves to another contract: ", declared)
            );
        }
    }

    /// PROPERTY: every snapshot declares exactly the five constants a deploy
    /// record is for, of these types, in this order. A rename, a retype, a
    /// reorder or a sixth constant each fail here and name what broke.
    ///
    /// `DEPENDENCIES` is `bytes` rather than `address[]` because Solidity has
    /// no file-scope constant of dynamic array type. It is the `abi.encode` of
    /// the list, which `releasedLibraryBlock` emits the `abi.decode` of — the
    /// type is a language constraint, so it is asserted here as one rather than
    /// left to look like a choice somebody could tidy up.
    function testSnapshotDeclaresTheFiveDeployConstantsInOrder() external view {
        string[] memory contractNames = snapshotContractNames();
        for (uint256 i = 0; i < contractNames.length; i++) {
            string[] memory declarations = constantDeclarations(contractNames[i]);

            assertEq(declarations.length, 5, "snapshot declares an unexpected number of constants");
            assertEq(declarations[0], "bytes32 BYTECODE_HASH", "first constant is not bytes32 BYTECODE_HASH");
            assertEq(declarations[1], "address DEPLOYED_ADDRESS", "second constant is not address DEPLOYED_ADDRESS");
            assertEq(declarations[2], "bytes CREATION_CODE", "third constant is not bytes CREATION_CODE");
            assertEq(declarations[3], "bytes RUNTIME_CODE", "fourth constant is not bytes RUNTIME_CODE");
            assertEq(declarations[4], "bytes DEPENDENCIES", "fifth constant is not bytes DEPENDENCIES");
        }
    }

    /// PROPERTY: a snapshot imports nothing. It is read by repos that do not
    /// have the contract it describes — that is the whole reason a frozen
    /// release stays verifiable after its source has changed or gone — so any
    /// import would make it unusable to exactly the readers it exists for.
    function testSnapshotImportsNothing() external view {
        string[] memory contractNames = snapshotContractNames();
        for (uint256 i = 0; i < contractNames.length; i++) {
            string[] memory types = nodeTypes(contractNames[i]);
            for (uint256 j = 0; j < types.length; j++) {
                assertNotEq(types[j], "ImportDirective", "snapshot imports something");
            }
        }
    }

    /// PROPERTY: a snapshot declares no contract, library or interface. It is
    /// a record, not code; anything deployable in it would be a second
    /// definition of something the record is supposed to describe.
    function testSnapshotDeclaresNoContract() external view {
        string[] memory contractNames = snapshotContractNames();
        for (uint256 i = 0; i < contractNames.length; i++) {
            string[] memory types = nodeTypes(contractNames[i]);
            for (uint256 j = 0; j < types.length; j++) {
                assertNotEq(types[j], "ContractDefinition", "snapshot declares a contract");
            }
        }
    }

    /// PROPERTY: a snapshot says it is generated. Someone who opens it must
    /// be told not to hand-edit it, because hand-editing is how a deploy record
    /// stops describing the deployment.
    function testSnapshotSaysItIsGenerated() external view {
        string[] memory contractNames = snapshotContractNames();
        for (uint256 i = 0; i < contractNames.length; i++) {
            assertTrue(
                vm.contains(
                    vm.readFile(
                        LibRainDeploySnapshot.pathForSnapshot(LibRainDeploySnapshot.CANDIDATE, contractNames[i])
                    ),
                    GENERATED_HEADER
                ),
                "snapshot is missing the generated-file header"
            );
        }
    }
}
